### ISSUE TITLE
Formuler / Dreamlink buttons Not Working Ok And Back Plus Up, Downtown Left Right Fix

### ISSUE THREAD

**Issue by ians325** [xbmc/peripheral.joystick#159]
Formuler / Dreamlink Remote buttons  Not Working Ok And Back Up, Down Left Right Fix.

This Layout will fix this and assign to correct buttons.

Hi_keyboard_v0001_p0001_23b.xml
https://pastebin.com/xkYxqJgG

**Comment by garbear** [comment]
Thanks for your contribution! Can you make a PR or should I?

**Comment by ians325** [comment]
Will Let U !!! This Version 1,

**Comment by ians325** [comment]
How to I go about about assign buttons Info and stuff like that

**Comment by ians325** [comment]
Ill Make buttons List from !!! That might be easier

**Comment by garbear** [comment]
Fixed by https://github.com/xbmc/peripheral.joystick/pull/161
