### ISSUE TITLE
kodi leia built with peripheral.joystick addon does not startup

### ISSUE THREAD

**Issue by Paulemann** [xbmc/peripheral.joystick#168]
A fresh built of kodi leia (May 2) with recent commits of peripheral.joystick doesn't startup on Ubuntu 18.04. I tried starting with no/empty .kodi folder which didn't help. Eventually I removed peripheral.joystick folder from /usr/local/lib/kodi/addon directory and kodi started up again.

**Comment by candrews** [comment]
Using 9ef67e results in Kodi starting and working.
Using ca8ea result in Kodi hanging on the splash screen.

This means the problem is definitely caused by #167

**Comment by DaVukovic** [comment]
confirmed

Same problem here while using Ubuntu

debug log: http://paste.ubuntu.com/p/vDrF7Ww63G/
