### ISSUE TITLE
How to use two unit of Xbox One Controller connected via Bluetooth?

### ISSUE THREAD

**Issue by chchia** [xbmc/peripheral.joystick#172]
Hi all, it is so great about the game feature, now may HTPC had really become the center of my living room.

Using one unit of Xbox Wireless Controller connected by Bluetooth was running greatly.

however i am having problem when connect the second Xbox Wireless Controller by Bluetooth, it seems both controller have same key mapping and both controller only control player one, i cannot have the second controller for second player.

appreciate if some one can provide a guide for me showing how to setup correctly.

good day!

**Comment by garbear** [comment]
Closing this alongside https://github.com/xbmc/xbmc/issues/15765 completed in 2023. We now have a full Player Viewer that shows multiple controllers can work to control games.
