### ISSUE TITLE
Joystick Support not compatible with latest PPA Kodi version 19.0-ALPHA1 (18.9.701)

### ISSUE THREAD

**Issue by johnclund** [xbmc/peripheral.joystick#184]
Hi,

I recently installed the latest Kodi version (Matrix - 19.0-ALPHA1 (18.9.701)) on Ubuntu-Mate 20.04.1 from the PPA according to the Kodi instructions, and I'm trying to get my PS4 controller to work. But when I try to enable the joystick support plugin, I get the error that the Joystick Support add-on in not compatible with my version of Kodi. I see that the add-on version installed with my version of Kodi is 1.5.2. But I can see here that there is a 1.6 version available, but when I try to run the update from inside Kodi it says that not updates are available.

Am I missing something obvious? How can I get Kodi to pick up the new version of this add-on and install it? Is there something else going wrong?

Thanks so much for you great work! :)
John

**Comment by garbear** [comment]
@AlwinEsch do we need to tag a new version?

**Comment by AlwinEsch** [comment]
Yes, there on begin I'm not thought about delayed kodi build for his Ubuntu packages.

To retrigger his build and allow update by users another another version needed.

Maybe I can also trigger his debian build on PPA and look if he increase his build version (the 4. Number there on version).

Let me check this evening update.

**Comment by AlwinEsch** [comment]
I do a new release about has wrongly used 1.5.3 in xml and 1.6.0 in release.

**Comment by AlwinEsch** [comment]
The new version is released, if nothing goes wrong should it in next hours available on Ubuntu PPA.

**EDIT:**
All three distrubtion builds was now OK https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly/+packages?field.name_filter=peripheral-joystick&field.status_filter=published&field.series_filter= only then need to make his deploy.

**Comment by garbear** [comment]
thanks!

**Comment by johnclund** [comment]
It's working now. Thank you!
