### ISSUE TITLE
Question : Is this plugin still needed with Kodi 19.0 ?

### ISSUE THREAD

**Issue by LeRatierBretonnien** [xbmc/peripheral.joystick#188]
Thansk for answering. :)

**Comment by lrusak** [comment]
yes

**Comment by LeRatierBretonnien** [comment]
OK, thanks, but i am unable to find it in the various repo. Where can i get it ?

**Comment by lrusak** [comment]
it's either shipped with kodi for some platforms or for linux it's provided by your linux distribution package manager
