### ISSUE TITLE
Default PS4 controller buttonmap doesn't match my controller

### ISSUE THREAD

**Issue by arucard21** [xbmc/peripheral.joystick#66]
I assume that with the PS4 buttonmap now added to the addon, if my PS4 controller were detected as a match for it, I wouldn't need to go through the controller configuration before being able to use the controller. Is this correct?

I installed this latest git version with Kodi 17.0-beta6 and I noticed that I still had to go through the controller configuration where my PS4 controller was (still) being recognized as having 14 buttons and 18 axes. Even after removing all my userdata for the peripheral.joystick addon and restarting Kodi, I had to go through the controller configuration again and the new buttonmap files still ended with 14b_18a (both with wireless and wired connection). 

Is this buttonmap file for a different version/variation of the controller perhaps? Mine is actually detected as "Wireless Controller" (when connected with Bluetooth) or "Sony Computer Entertainment Wireless Controller" (when connected with USB). It might be relevant to mention that I'm on Linux (Debian unstable, with self-compiled Kodi).

**Comment by garbear** [comment]
ATM every unique controller needs its own button map. This means that if two PS4 controllers are named "Wireless Controller" and "Wireless Controller PS4", they will each need their own separate button map. If you want your controller to be mapped out-of-the-box, create a button map for it and send a PR to this repo.

In the future, peripheral.joystick will be able to recognize that controllers are similar if they have the same number of buttons/axes and use the button map even if the controller is named different. For now, though, each controller needs its own button map.

**Comment by arucard21** [comment]
I created PR #68 with my buttonmap. Hope it helps with the out-of-the-box experience.

**Comment by arucard21** [comment]
Since the buttonmaps are now merged, I'm closing this issue.
