### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by candrews** [xbmc/peripheral.joystick#74]
According to https://github.com/xbmc/peripheral.joystick/blob/master/peripheral.joystick/addon.xml.in, the current version is 1.2.0. Can you please tag this release?

Releases make things a lot easier for distributions (in my case, Gentoo) to package the add-on.

Thanks!

**Comment by garbear** [comment]
Version has been tagged for Krypton release: https://github.com/xbmc/peripheral.joystick/releases/tag/v1.2.1

@MartijnKaijser
