### ISSUE TITLE
invalid conversion from ‘int’ to ‘JOYSTICK_DRIVER_PRIMITIVE_TYPE’

### ISSUE THREAD

**Issue by candrews** [xbmc/peripheral.joystick#91]
Using peripherial.joystick 1.2.1 and Kodi 17:
`
/var/tmp/portage/media-plugins/kodi-peripheral-joystick-1.2.1/work/peripheral.joystick-1.2.1/src/buttonmapper/ButtonMapTranslator.cpp: In static member function ‘static ADDON::DriverPrimitive JOYSTICK::ButtonMapTranslator::ToDriverPrimitive(const string&, JOYSTICK_DRIVER_PRIMITIVE_TYPE)’: /var/tmp/portage/media-plugins/kodi-peripheral-joystick-1.2.1/work/peripheral.joystick-1.2.1/src/buttonmapper/ButtonMapTranslator.cpp:100:53: error: invalid conversion from ‘int’ to ‘JOYSTICK_DRIVER_PRIMITIVE_TYPE’ [-fpermissive]
         primitive = ADDON::DriverPrimitive(std::atoi(strPrimitive.substr(1).c_str()), dir);
                                                     ^
In file included from /var/tmp/portage/media-plugins/kodi-peripheral-joystick-1.2.1/work/peripheral.joystick-1.2.1/src/buttonmapper/ButtonMapTranslator.h:22:0
`

Originally reported at https://bugs.gentoo.org/show_bug.cgi?id=612074

**Comment by garbear** [comment]
This is because you're building peripheral.joystick 1.2.1 against Kodi's peripheral API at 1.3.1. I'll tag a v1.3.1 version of peripheral.joystick that will compile against the latest Kodi 17 and 18 branches

**Comment by garbear** [comment]
OK, please try v1.3.1. This should work against the latest Krypton RC branch and Leia.

You can see which version of peripheral.joystick is required by looking in this file: https://github.com/xbmc/xbmc/blob/master/addons/kodi.peripheral/addon.xml

**Comment by candrews** [comment]
Would I bet correct in saying that joystick 1.2.1 should be used with Kodi 16, and joystick 1.3.1 should be used with 17 and 18?

**Comment by garbear** [comment]
No. The new joystick abstractions that peripheral.joystick uses were added in v17.

Specifically, Kodi v17.0 (commit  a10c504) should use 1.2.1. Everything else will probably need 1.3.1. You can find out for sure by checking that xml file I linked to.
